а
test

diff --git a/.github/workflows/build-publish-lib.yml b/.github/workflows/build-publish-lib.yml
--- a/.github/workflows/build-publish-lib.yml
+++ b/.github/workflows/build-publish-lib.yml
@@ -1,6 +1,15 @@
 name: Build and Publish the Library
 on:
-  workflow_dispatch
+  workflow_dispatch:
+    inputs:
+      version:
+        description: Whether it's a patch, minor or major release
+        required: true
+        type: choice
+        options:
+          - major
+          - minor
+          - patch
 
 jobs:
   build-and-deploy-lib:
@@ -20,19 +29,6 @@ jobs:
           architecture: x64
           registry-url: "https://registry.npmjs.org"
 
-      - name: Get version
-        id: package-version
-        uses: martinbeentjes/npm-get-version-action@v1.1.0
-
-      - name: Check tag does not exist yet
-        run: if git rev-list v${{ steps.package-version.outputs.current-version }}; then echo "Tag already exists. Aborting the release process."; exit 1; fi
-
-      - name: Tag commit and push
-        uses: mathieudutour/github-tag-action@v5.6
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          custom_tag: ${{ steps.package-version.outputs.current-version }}
-
       - name: Install and link 🔗
         run: |
           npm ci
@@ -49,6 +45,23 @@ jobs:
         run: |
           npm run build
 
+      - name: Bump version
+        run: |
+          npm version ${{ github.event.inputs.version }}
+
+      - name: Get version
+        id: package-version
+        uses: martinbeentjes/npm-get-version-action@v1.1.0
+
+      - name: Check tag does not exist yet
+        run: if git rev-list v${{ steps.package-version.outputs.current-version }}; then echo "Tag already exists. Aborting the release process."; exit 1; fi
+
+      - name: Tag commit and push
+        uses: mathieudutour/github-tag-action@v5.6
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          custom_tag: ${{ steps.package-version.outputs.current-version }}
+
       - name: Publish NPM package (regular)
         if: ${{ steps.prepare_release.outputs.release_type == 'regular' }}
         run: |
@@ -56,7 +69,7 @@ jobs:
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_ORG_TOKEN }}
 
-      - name: Publish NPM package (pre-release)
+      - name: Publish NPM package (prerelease)
         if: ${{ steps.prepare_release.outputs.release_type == 'prerelease' }}
         run: |
           npm publish --tag next --access public --non-interactive
